name: modeleRecoPlaque
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.4
  - ld_impl_linux-64=2.44
  - libexpat=2.7.4
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.19
  - packaging=25.0
  - pip=26.0.1
  - pthread-stubs=0.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.10.2
  - sqlite=3.51.1
  - tk=8.6.15
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - asttokens==3.0.1
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - debugpy==1.8.20
      - decorator==5.2.1
      - easyocr==1.7.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - filelock==3.24.3
      - fonttools==4.61.1
      - fsspec==2026.2.0
      - idna==3.11
      - imageio==2.37.2
      - ipykernel==6.29.5
      - ipython==8.38.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jupyter-client==8.8.0
      - jupyter-core==5.9.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - markupsafe==3.0.3
      - matplotlib==3.7.2
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.13.0
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - pandas==2.0.3
      - parso==0.8.6
      - pexpect==4.9.0
      - pillow==9.5.0
      - platformdirs==4.9.2
      - polars==1.38.1
      - polars-runtime-32==1.38.1
      - prompt-toolkit==3.0.52
      - psutil==7.2.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyclipper==1.4.0
      - pygments==2.19.2
      - pyparsing==3.0.9
      - python-bidi==0.6.7
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - requests==2.32.5
      - scikit-image==0.24.0
      - scipy==1.15.3
      - shapely==2.1.2
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - tifffile==2025.5.10
      - torch==2.4.1
      - torchvision==0.19.1
      - tornado==6.5.4
      - traitlets==5.14.3
      - triton==3.0.0
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - ultralytics==8.4.14
      - ultralytics-thop==2.0.18
      - urllib3==2.6.3
      - wcwidth==0.6.0
prefix: /home/nathan/miniconda3/envs/modeleRecoPlaque
